server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: movie-route
              uri: ${MOVIE_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/movies/**